name: Daily GitHub Commit Check

on:
  schedule:
    - cron: "0 14 * * *" # বাংলাদেশ সময় রাত ৮টা (UTC +6)
  workflow_dispatch:

jobs:
  check_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install axios twilio dotenv

      - name: Create .env file
        run: |
          echo "GITHUB_USERNAME=${{ secrets.GITHUB_USERNAME }}" >> .env
          echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> .env
          echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> .env
          echo "TO_WHATSAPP=${{ secrets.TO_WHATSAPP }}" >> .env
          echo "FROM_WHATSAPP=${{ secrets.FROM_WHATSAPP }}" >> .env

      - name: Run Commit Check Script
        run: node index.js
